[project]
name = "websockets-task"
version = "0.1.0"
description = "Websockets server to stream p5js data"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.122.0",
    "uvicorn[standard]>=0.38.0",
]
